package com.attempttracker;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import net.runelite.api.Skill;
import net.runelite.api.gameval.AnimationID;

/** Explicit gathering animation catalog using RuneLite's named game values. */
final class AnimationCatalog
{
	private static final Map<Integer, String> NAMES = new HashMap<>();
	private static final Map<Integer, Skill> SKILLS = new HashMap<>();
	static
	{
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_AXE_NO_INFERNAL, "HUMAN_WOODCUTTING_TRAILBLAZER_AXE_NO_INFERNAL");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_TRAILBLAZER_NO_INFERNAL, "HUMAN_HARPOON_TRAILBLAZER_NO_INFERNAL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL, "HUMAN_MINING_DRAGON_PICKAXE_PRETTY_WALL");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON, "HUMAN_HARPOON");
		register(Skill.FISHING, AnimationID.HUMAN_LOBSTER, "HUMAN_LOBSTER");
		register(Skill.FISHING, AnimationID.HUMAN_LARGENET, "HUMAN_LARGENET");
		register(Skill.FISHING, AnimationID.HUMAN_SMALLNET, "HUMAN_SMALLNET");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING, "HUMAN_FISHING_CASTING");
		register(Skill.FISHING, AnimationID.HUMAN_FISH_ONSPOT, "HUMAN_FISH_ONSPOT");
		register(Skill.MINING, AnimationID.HUMAN_MINING_RUNE_PICKAXE, "HUMAN_MINING_RUNE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BRONZE_PICKAXE, "HUMAN_MINING_BRONZE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_IRON_PICKAXE, "HUMAN_MINING_IRON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_STEEL_PICKAXE, "HUMAN_MINING_STEEL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ADAMANT_PICKAXE, "HUMAN_MINING_ADAMANT_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_MITHRIL_PICKAXE, "HUMAN_MINING_MITHRIL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY, "HUMAN_MINING_DRAGON_PICKAXE_PRETTY");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE_PRETTY_NOREACHFORWARD, "HUMAN_MINING_DRAGON_PICKAXE_PRETTY_NOREACHFORWARD");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_RUNE_AXE, "HUMAN_WOODCUTTING_RUNE_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_ADAMANT_AXE, "HUMAN_WOODCUTTING_ADAMANT_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_MITHRIL_AXE, "HUMAN_WOODCUTTING_MITHRIL_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_BLACK_AXE, "HUMAN_WOODCUTTING_BLACK_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_STEEL_AXE, "HUMAN_WOODCUTTING_STEEL_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_IRON_AXE, "HUMAN_WOODCUTTING_IRON_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_BRONZE_AXE, "HUMAN_WOODCUTTING_BRONZE_AXE");
		register(Skill.FISHING, AnimationID.HUMAN_OCTOPUS_POT, "HUMAN_OCTOPUS_POT");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_INFERNAL_AXE, "HUMAN_WOODCUTTING_INFERNAL_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_DRAGON_AXE, "HUMAN_WOODCUTTING_DRAGON_AXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BLACK_PICKAXE_WALL, "HUMAN_MINING_BLACK_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BLACK_PICKAXE, "HUMAN_MINING_BLACK_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_WALL, "HUMAN_MINING_INFERNAL_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_INFERNAL_PICKAXE, "HUMAN_MINING_INFERNAL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_INFERNAL_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_INFERNAL_PICKAXE_NOREACHFORWARD");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_BARBED, "HUMAN_HARPOON_BARBED");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_BLESSED_AXE, "HUMAN_WOODCUTTING_BLESSED_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_BLESSED_AXE_MISS, "HUMAN_WOODCUTTING_BLESSED_AXE_MISS");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BLACK_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_BLACK_PICKAXE_NOREACHFORWARD");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_START, "BRUT_PLAYER_HAND_FISHING_START");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_READY, "BRUT_PLAYER_HAND_FISHING_READY");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_SHARK_2, "BRUT_PLAYER_HAND_FISHING_END_SHARK_2");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_SHARK_1, "BRUT_PLAYER_HAND_FISHING_END_SHARK_1");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_1, "BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_1");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_2, "BRUT_PLAYER_HAND_FISHING_END_SWORDFISH_2");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_BLANK, "BRUT_PLAYER_HAND_FISHING_END_BLANK");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_TUNA_1, "BRUT_PLAYER_HAND_FISHING_END_TUNA_1");
		register(Skill.FISHING, AnimationID.BRUT_PLAYER_HAND_FISHING_END_TUNA_2, "BRUT_PLAYER_HAND_FISHING_END_TUNA_2");
		register(Skill.MINING, AnimationID.HUMAN_MINING_RUNE_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_RUNE_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BRONZE_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_BRONZE_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_IRON_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_IRON_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_STEEL_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_STEEL_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_ADAMANT_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_MITHRIL_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_RUNE_PICKAXE_WALL, "HUMAN_MINING_RUNE_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_BRONZE_PICKAXE_WALL, "HUMAN_MINING_BRONZE_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_IRON_PICKAXE_WALL, "HUMAN_MINING_IRON_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_STEEL_PICKAXE_WALL, "HUMAN_MINING_STEEL_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ADAMANT_PICKAXE_WALL, "HUMAN_MINING_ADAMANT_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_MITHRIL_PICKAXE_WALL, "HUMAN_MINING_MITHRIL_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE_WALL, "HUMAN_MINING_DRAGON_PICKAXE_WALL");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_PEARL_OILY, "HUMAN_FISHING_CASTING_PEARL_OILY");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE, "HUMAN_MINING_DRAGON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DRAGON_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_DRAGON_PICKAXE_NOREACHFORWARD");
		register(Skill.FISHING, AnimationID.HUMAN_FISH_ONSPOT_PEARL_OILY, "HUMAN_FISH_ONSPOT_PEARL_OILY");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_3A_AXE, "HUMAN_WOODCUTTING_3A_AXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_3A_PICKAXE_WALL, "HUMAN_MINING_3A_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_3A_PICKAXE, "HUMAN_MINING_3A_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_3A_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_3A_PICKAXE_NOREACHFORWARD");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_DRAGON, "HUMAN_HARPOON_DRAGON");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_INFERNAL, "HUMAN_HARPOON_INFERNAL");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_PEARL, "HUMAN_FISHING_CASTING_PEARL");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_PEARL_FLY, "HUMAN_FISHING_CASTING_PEARL_FLY");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_PEARL_BRUT, "HUMAN_FISHING_CASTING_PEARL_BRUT");
		register(Skill.FISHING, AnimationID.HUMAN_FISH_ONSPOT_PEARL, "HUMAN_FISH_ONSPOT_PEARL");
		register(Skill.FISHING, AnimationID.HUMAN_FISH_ONSPOT_PEARL_FLY, "HUMAN_FISH_ONSPOT_PEARL_FLY");
		register(Skill.FISHING, AnimationID.HUMAN_FISH_ONSPOT_PEARL_BRUT, "HUMAN_FISH_ONSPOT_PEARL_BRUT");
		register(Skill.FISHING, AnimationID.AERIAL_FISHING_LAUNCH, "AERIAL_FISHING_LAUNCH");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_GILDED_AXE, "HUMAN_WOODCUTTING_GILDED_AXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_GILDED_PICKAXE_WALL, "HUMAN_MINING_GILDED_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_GILDED_PICKAXE, "HUMAN_MINING_GILDED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_GILDED_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_GILDED_PICKAXE_NOREACHFORWARD");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_CRYSTAL_AXE, "HUMAN_WOODCUTTING_CRYSTAL_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_GAUNTLET_AXE_HM, "HUMAN_WOODCUTTING_GAUNTLET_AXE_HM");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_CRYSTAL, "HUMAN_HARPOON_CRYSTAL");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_GAUNTLET_HM, "HUMAN_HARPOON_GAUNTLET_HM");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_WALL, "HUMAN_MINING_ZALCANO_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_WALL, "HUMAN_MINING_CRYSTAL_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_PICKAXE, "HUMAN_MINING_ZALCANO_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE, "HUMAN_MINING_CRYSTAL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_GAUNTLET_PICKAXE_HM, "HUMAN_MINING_GAUNTLET_PICKAXE_HM");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_ZALCANO_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_CRYSTAL_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_CRYSTAL_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_BRONZE_PICKAXE, "HUMAN_MINING_ZALCANO_BRONZE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_IRON_PICKAXE, "HUMAN_MINING_ZALCANO_IRON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_BLACK_PICKAXE, "HUMAN_MINING_ZALCANO_BLACK_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_STEEL_PICKAXE, "HUMAN_MINING_ZALCANO_STEEL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_MITHRIL_PICKAXE, "HUMAN_MINING_ZALCANO_MITHRIL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_ADAMANT_PICKAXE, "HUMAN_MINING_ZALCANO_ADAMANT_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_RUNE_PICKAXE, "HUMAN_MINING_ZALCANO_RUNE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_GILDED_PICKAXE, "HUMAN_MINING_ZALCANO_GILDED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_DRAGON_PICKAXE, "HUMAN_MINING_ZALCANO_DRAGON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_DRAGON_PICKAXE_PRETTY, "HUMAN_MINING_ZALCANO_DRAGON_PICKAXE_PRETTY");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_ZALCANO_PICKAXE, "HUMAN_MINING_ZALCANO_ZALCANO_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_INFERNAL_PICKAXE, "HUMAN_MINING_ZALCANO_INFERNAL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_3A_PICKAXE, "HUMAN_MINING_ZALCANO_3A_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_CRYSTAL_PICKAXE, "HUMAN_MINING_ZALCANO_CRYSTAL_PICKAXE");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_TRAILBLAZER, "HUMAN_HARPOON_TRAILBLAZER");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_LEAGUE_TRAILBLAZER, "HUMAN_HARPOON_LEAGUE_TRAILBLAZER");
		register(Skill.MINING, AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL, "HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE, "HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_LEAGUE_TRAILBLAZER_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_LEAGUE_TRAILBLAZER_PICKAXE, "HUMAN_MINING_ZALCANO_LEAGUE_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL, "HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL, "HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_NOREACHFORWARD, "HUMAN_MINING_TRAILBLAZER_PICKAXE_NO_INFERNAL_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE_NO_INFERNAL, "HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE_NO_INFERNAL");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_BRUT, "HUMAN_FISHING_CASTING_BRUT");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_ONSPOT_BRUT, "HUMAN_FISHING_ONSPOT_BRUT");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_BRONZE_PICKAXE, "HUMAN_MINING_HET_BRONZE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_IRON_PICKAXE, "HUMAN_MINING_HET_IRON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_BLACK_PICKAXE, "HUMAN_MINING_HET_BLACK_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_STEEL_PICKAXE, "HUMAN_MINING_HET_STEEL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_MITHRIL_PICKAXE, "HUMAN_MINING_HET_MITHRIL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_ADAMANT_PICKAXE, "HUMAN_MINING_HET_ADAMANT_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_RUNE_PICKAXE, "HUMAN_MINING_HET_RUNE_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_GILDED_PICKAXE, "HUMAN_MINING_HET_GILDED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_DRAGON_PICKAXE, "HUMAN_MINING_HET_DRAGON_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_DRAGON_PICKAXE_PRETTY, "HUMAN_MINING_HET_DRAGON_PICKAXE_PRETTY");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_ZALCANO_PICKAXE, "HUMAN_MINING_HET_ZALCANO_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_INFERNAL_PICKAXE, "HUMAN_MINING_HET_INFERNAL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_3A_PICKAXE, "HUMAN_MINING_HET_3A_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_CRYSTAL_PICKAXE, "HUMAN_MINING_HET_CRYSTAL_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_LEAGUE_TRAILBLAZER_PICKAXE, "HUMAN_MINING_HET_LEAGUE_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_TRAILBLAZER_PICKAXE_NO_INFERNAL, "HUMAN_MINING_HET_TRAILBLAZER_PICKAXE_NO_INFERNAL");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_BRONZE, "FORESTRY_2H_AXE_CHOPPING_BRONZE");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_IRON, "FORESTRY_2H_AXE_CHOPPING_IRON");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_STEEL, "FORESTRY_2H_AXE_CHOPPING_STEEL");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_BLACK, "FORESTRY_2H_AXE_CHOPPING_BLACK");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_MITHRIL, "FORESTRY_2H_AXE_CHOPPING_MITHRIL");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_ADAMANT, "FORESTRY_2H_AXE_CHOPPING_ADAMANT");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_RUNE, "FORESTRY_2H_AXE_CHOPPING_RUNE");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_DRAGON, "FORESTRY_2H_AXE_CHOPPING_DRAGON");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_CRYSTAL, "FORESTRY_2H_AXE_CHOPPING_CRYSTAL");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_CRYSTAL_INACTIVE, "FORESTRY_2H_AXE_CHOPPING_CRYSTAL_INACTIVE");
		register(Skill.WOODCUTTING, AnimationID.FORESTRY_2H_AXE_CHOPPING_3A, "FORESTRY_2H_AXE_CHOPPING_3A");
		register(Skill.FISHING, AnimationID.HUMAN_LARGENET_LOOPING, "HUMAN_LARGENET_LOOPING");
		register(Skill.FISHING, AnimationID.HUMAN_FISHING_CASTING_NPC, "HUMAN_FISHING_CASTING_NPC");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL, "HUMAN_MINING_TRAILBLAZER_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_WALL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE, "HUMAN_MINING_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_TRAILBLAZER_PICKAXE, "HUMAN_MINING_HET_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE, "HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL, "HUMAN_MINING_HET_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_TRAILBLAZER_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NOREACHFORWARD, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_NOREACHFORWARD, "HUMAN_MINING_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL_NOREACHFORWARD");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE, "HUMAN_MINING_ZALCANO_TRAILBLAZER_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE, "HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL, "HUMAN_MINING_ZALCANO_TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED, "HUMAN_HARPOON_TRAILBLAZER_RELOADED");
		register(Skill.FISHING, AnimationID.HUMAN_HARPOON_TRAILBLAZER_RELOADED_NO_INFERNAL, "HUMAN_HARPOON_TRAILBLAZER_RELOADED_NO_INFERNAL");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE, "HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE_NO_INFERNAL, "HUMAN_WOODCUTTING_TRAILBLAZER_RELOADED_AXE_NO_INFERNAL");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_LEAGUE_AXE, "HUMAN_WOODCUTTING_LEAGUE_AXE");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_TRAILBLAZER_AXE, "HUMAN_WOODCUTTING_TRAILBLAZER_AXE");
		register(Skill.MINING, AnimationID.HUMAN_MINING_DEMONIC_PACT, "HUMAN_MINING_DEMONIC_PACT");
		register(Skill.WOODCUTTING, AnimationID.HUMAN_WOODCUTTING_DEMONIC_PACT, "HUMAN_WOODCUTTING_DEMONIC_PACT");
	}

	private static void register(Skill skill, int animation, String name)
	{
		SKILLS.put(animation, skill);
		NAMES.put(animation, name);
	}

	private AnimationCatalog() { }
	static Skill skillFor(int animation) { return SKILLS.get(animation); }
	static boolean isHarpoon(int animation) { return NAMES.getOrDefault(animation, "").startsWith("HUMAN_HARPOON"); }
	static String methodFor(int animation)
	{
		String name = NAMES.getOrDefault(animation, "Animation " + animation);
		if (name.startsWith("BRUT_PLAYER_HAND_FISHING_")) { return "bare hand fishing"; }
		if (name.startsWith("HUMAN_LARGENET")) { return "large net"; }
		// Casting and the subsequent fishing pose belong to the same method.
		name = name.replace("HUMAN_FISHING_CASTING", "FISHING_ROD").replace("HUMAN_FISHING_ONSPOT", "FISHING_ROD").replace("HUMAN_FISH_ONSPOT", "FISHING_ROD");
		return name.replace("HUMAN_", "").replace('_', ' ').toLowerCase(Locale.ROOT);
	}
}
